### ISSUE TITLE
error on startup 

### ISSUE THREAD

**Issue by Jonas-Alker** [bohning/usdb_syncer#258] opened 2024-07-03 11:51 UTC
Hey, I used the program a few months ago, but now I get the error message shown in the picture when I start it. Since it is an incorrectly set integer, I think it is due to a faulty file. I have already tried to find all the files that have something to do with the project and then delete them, but apparently I couldn't find them all. Is it possible to completely uninstall the program or can you tell me where the files are stored?
Thanks in advance 

Translated with DeepL.com (free version)![Screenshot 2024-07-03 134632](https://github.com/bohning/usdb_syncer/assets/74871226/ceb3948c-3905-4fed-b351-83e34e075c24)

**Comment by theRoboxx** [comment] 2024-07-03 14:20
Could you release a new executable version?

**Comment by bohning** [comment] 2024-07-03 14:24
USDB has changed a bit, and the Syncer needs to adapt to the changes. It's being worked on. Meanwhile, here's a way to support the programmers: https://buymeacoffee.com/usdbsyncer ;-)

**Comment by SteveW94** [comment] 2024-07-03 16:37
As this is a duplicate of my Issue #253, thanks to the fast response of the Devs, the fix is already merged to the main branch, but no release is built yet.

In the meantime @theRoboxx and @Jonas-Alker you could checkout the repo and launch it from there, via the rather well descriped tuorial in the README.

This one works already just fine :)

On the other hand...some coffee for the Devs is also always fine I guess ;P

**Comment by Wussatier** [comment] 2024-07-09 15:50
@SteveW94 I'm able to run it via the repo. Do you know how I can compile the code so that I get an exe?

**Comment by SteveW94** [comment] 2024-07-09 19:15
@Wussatier No, sadly I do not :/

I have no real experience with python projects and their building yet I have to admit.

**Comment by RumovZ** [comment] 2024-07-11 20:24
Fixed with 0.6.0.

**Closed by RumovZ** 2024-07-11 20:24 UTC
