### ISSUE TITLE
Bulk downloading songs causes "sqlite3.InterfaceError: bad parameter or other API misuse"

### ISSUE THREAD

**Issue by randompersona1** [bohning/usdb_syncer#277] opened 2024-08-22 15:13 UTC
Bulk downloading a large enough number of songs causes an exception, freezing the window entirely. It occurs only when attempting to download ~>200 songs. It also only seems to occur when the download is the first download in this session. It doesn't seem to be related to any number of particular songs. This was initially reported by someone else, but I have been able to reproduce the error.

The full stacktrace is 
```
Traceback (most recent call last):
      File "C:\repos\usdb_syncer\src\usdb_syncer\gui\song_table\table_model.py", line 91, in data
    if song := self._get_song(index):
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\repos\usdb_syncer\src\usdb_syncer\gui\song_table\table_model.py", line 99, in _get_song
    if song := UsdbSong.get(song_id):
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\repos\usdb_syncer\src\usdb_syncer\usdb_song.py", line 103, in get
    if row := db.get_usdb_song(song_id):
              ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\repos\usdb_syncer\src\usdb_syncer\db\__init__.py", line 480, in get_usdb_song
    return _DbState.connection().execute(stmt, (song_id,)).fetchone()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    sqlite3.InterfaceError: bad parameter or other API misuse

raceback (most recent call last):
      File "C:\repos\usdb_syncer\src\usdb_syncer\gui\progress.py", line 85, in wrapped_on_done
    on_done(result)
      File "C:\repos\usdb_syncer\src\usdb_syncer\gui\progress.py", line 60, in <lambda>
    on_done: Callable[[Result[T]], Any] = lambda res: res.result(),
                                                      ^^^^^^^^^^^^
      File "C:\repos\usdb_syncer\src\usdb_syncer\gui\progress.py", line 35, in result
    raise self._result.error
      File "C:\repos\usdb_syncer\src\usdb_syncer\gui\progress.py", line 77, in wrapped_task
    result = Result(task())
                    ^^^^^^
      File "C:\repos\usdb_syncer\src\usdb_syncer\gui\song_table\song_table.py", line 112, in _download_inner
    assert song
           ^^^^
    AssertionError
```
    
Debugging `db/__init__.py::get_usdb_song` with a print statement reveals a seemingly completely regular and correct sql command right before the error. This isn't reliable, as changing the method sometimes causes the error to disappear. However, if the error appears with a certain configuration, it will always appear with that configuration. 

https://github.com/user-attachments/assets/54f449d6-8826-46ef-b16a-57310a1daed3

**Comment by randompersona1** [comment] 2024-08-24 16:43
For me, nothing has changed with #279. 

To reproduce: 
start syncer
filter for polish
click on any song, then ctrl-a to select all
use download button or rightclick -> download

As long as I don't touch the code, I can reproduce reliably

**Comment by RumovZ** [comment] 2024-08-24 18:54
Thanks for testing.
I can't reproduce the issue like this. Do you have already downloaded those songs?

**Comment by randompersona1** [comment] 2024-08-24 19:23
No.

I am running windows and tested on both 3.12.4 and 3.12.5.

After just removing and readding my venv, I can't even start the syncer on the `sqlite-error` branch. The main branch works fine, apart from the original error. This wasn't the case before changing the venv.
```
C:\Users\<redacted>\usdb_syncer_bohning [sqlite-error ≡ +1 ~1 -0 !]> poetry run usdb_syncer
2024-08-24 21:13:23 [ERROR] Uncaught exception:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\<redacted>\usdb_syncer_bohning\src\usdb_syncer\gui\__init__.py", line 50, in main
    _run()
      File "C:\Users\<redacted>\usdb_syncer_bohning\src\usdb_syncer\gui\__init__.py", line 60, in _run
    _load_main_window(mw)
      File "C:\Users\<redacted>\usdb_syncer_bohning\src\usdb_syncer\gui\__init__.py", line 90, in _load_main_window
    db.connect(utils.AppPaths.db)
      File "C:\Users\<redacted>\usdb_syncer_bohning\src\usdb_syncer\db\__init__.py", line 113, in connect
    _DbState.connect(db_path, trace=bool(os.environ.get("TRACESQL")))
      File "C:\Users\<redacted>\usdb_syncer_bohning\src\usdb_syncer\db\__init__.py", line 63, in connect
    _validate_schema(cls._local.connection)
      File "C:\Users\<redacted>\usdb_syncer_bohning\src\usdb_syncer\db\__init__.py", line 109, in _validate_schema
    connection.executescript(_SqlCache.get("setup_session_script.sql", cache=False))
    sqlite3.OperationalError: cannot change into wal mode from within a transaction
```

Feeling some imposter syndrome. Can anybody else confirm either the original error on the any branch or this error on the `sqlite-error` branch?

**Comment by RumovZ** [comment] 2024-08-24 19:46
It's likely a race condition and by nature difficult to reproduce. I appreciate you taking the time to test it for us.
Changing the threading model was just a guess, apparently something else is causing this.

The other error was caused by the changes I made, should be fixed now.

**Comment by randompersona1** [comment] 2024-08-24 21:18
dea706192d9c77de62b974c460a97cbdfbdd2e04 in #279 fixed the issue for me. Tried multiple different configurations and methods and couldn't cause the error anymore.

**Comment by RumovZ** [comment] 2024-08-25 09:20
https://github.com/bohning/usdb_syncer/commit/dea706192d9c77de62b974c460a97cbdfbdd2e04 is just a linter configuration and has no effect on runtime behaviour. Actually, 7cb32bd is the only commit I would expect to make any difference.
Maybe there was some caching strangeness going on so it didn't work immediately. The WAL-mode error didn't appear immediately for me, either.

Anyway, let's hope the issue is gone for good with #279.

**Closed** 2024-08-25 09:28 UTC
Labels: bug
