### ISSUE TITLE
Code-sign artefact executables.

### ISSUE THREAD

**Issue by bohning** [bohning/usdb_syncer#90] opened 2023-01-29 12:04 UTC
Mac: https://gist.github.com/txoof/0636835d3cc65245c6288b2374799c43
Win: https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ms537361(v=vs.85)?redirectedfrom=MSDN

**Comment by Baklap4** [comment] 2023-05-30 18:28
Might also be neccesairy to add it to windows defender list for fast scanability instead of waiting for X amount of downloads 
can be done through: https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by RumovZ** [comment] 2024-09-07 09:24
Closing, as it turned out to be not really feasible for small projects.

**Closed by RumovZ** 2024-09-07 09:24 UTC
Labels: enhancement

**Comment by Baklap4** [comment] 2024-09-10 07:15
I know the issue is closed, but it might be feasable through SignPath + GH Actions fully automated for free (since this is an open source project): https://about.signpath.io/product/open-source
https://github.com/SignPath/github-actions

**Comment by RumovZ** [comment] 2024-09-17 15:19
Thanks, that's interesting.
However, I think the original motivation for this issue was to prevent or at least reduce the amount of security alerts users see, like Windows Defender blocking app execution. But it seems like the only thing that really helps with that is lots of people using an app.
So I wonder if this code signing would gain us anything.
